name: cWebSender
version: '1.1'
main: its.cactusdev.cWebSender.CWebSender
api-version: '1.21'
author: itscactusdev
description: WebSocket tabanlı Minecraft Paper eklentisi
softdepend: [PlaceholderAPI]
commands:
  cwebsender:
    description: CWebSender eklentisi ana komutu
    usage: /cwebsender [reload|status]
    permission: cwebsender.admin
permissions:
  cwebsender.admin:
    description: Tüm CWebSender komutlarına erişim sağlar
    default: op
  cwebsender.reload:
    description: CWebSender yapılandırmasını yeniden yükleme izni
    default: op
  cwebsender.status:
    description: CWebSender durum bilgisini görüntüleme izni
    default: op
