# CWebSender Yapılandırma Dosyası

# WebSocket sunucusunun çalışacağı port
websocket-port: 8080

# Debug modu (true/false)
# Debug modunda daha fazla log mesajı görüntülenir
debug-mode: false

# NOT: Kimlik doğrulama artık public/private key ile yapılmaktadır.
# Anahtar çifti otomatik olarak oluşturulacak ve 'keys' klasöründe saklanacaktır.
# İstemci tarafında, public key ile imzalanan mesajlar kullanılarak kimlik doğrulaması yapılmalıdır.

messages:
  errors:
    no-permission: "&cBu komutu kullanmak için yetkiniz yok!"
    player-not-found: "&cOyuncu bulunamadı!"

# Performans ayarları
performance:
  connection-pool-size: 10
  timeout: 30000

# WebSocket bağlantı ayarları
websocket:
  # Kimlik doğrulaması yapılmamış bağlantıların açık kalacağı maksimum süre (saniye cinsinden)
  connection-timeout-seconds: 300
  
  # Kimlik doğrulama nonce'larının geçerli kalacağı maksimum süre (saniye cinsinden)
  nonce-expiration-seconds: 300